[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.61.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://huangdiv.netlify.com/*"
  to = "https://huangdiv.com/:splat"
  force = true